#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=24:00:00
#PBS -N app-bids-hcppipeline-postFS

stage=PostFreeSurfer

fs=`jq -r '.freesurfer' config.json`
predat=`jq -r '.hcp_freesurferpre' config.json`

sub=$(jq -r "._inputs[0].meta.subject" config.json | tr -d "_")
if [[ -z $sub || $sub == null ]]; then
    sub=0
fi
bids_sub=sub-$sub

#organizing brainlife input to "bids" structure
cp -r $predat/output $bids_sub
cp -r $fs ${bids_sub}/T1w/${bids_sub}

singularity exec -e docker://brainlife/hcppipelines:0.1 \
    python ./run.py input ./ participant \
        --n_cpus 8 --stages $stage \
        --license_key "$FREESURFER_LICENSE" \
        --participant_label $sub

rtn=$?

#remove FS data
rm -rf ${bids_sub}/T1w/${bids_sub}
#relocate
mv ${bids_sub} output

exit $rtn
